---
- name: Install | Install additional packages
  ansible.builtin.apt:
    name:
      - adduser
      - libfontconfig1
    update_cache: yes
    state: present

- name: Install | Download Grafana package
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb"
    dest: "/tmp/grafana_{{ grafana_version }}_amd64.deb"
    mode: '0700'

- name: Install | Install Grafana
  ansible.builtin.apt:
    deb: "/tmp/grafana_{{ grafana_version }}_amd64.deb"
  notify: "start grafana"